/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package duan1_qlbantrasua.Views;

import duan1_qlbantrasua.DomainModels.CTGioHang;
import duan1_qlbantrasua.DomainModels.HoaDon;
import duan1_qlbantrasua.DomainModels.MucDa;
import duan1_qlbantrasua.DomainModels.MucDuong;
import duan1_qlbantrasua.DomainModels.SanPham;
import duan1_qlbantrasua.DomainModels.Topping;
import duan1_qlbantrasua.Services.CTGHServiece;
import duan1_qlbantrasua.Services.MucDaService;
import duan1_qlbantrasua.Services.MucDuongService;
import duan1_qlbantrasua.Services.ToppingService;
import duan1_qlbantrasua.Services.impl.CTGHServiceImpl;
import duan1_qlbantrasua.Services.impl.MucDaServiceImpl;
import duan1_qlbantrasua.Services.impl.MucDuongServiceImpl;
import duan1_qlbantrasua.Services.impl.ToppingServiceImpl;
import duan1_qlbantrasua.ViewModels.ChiTietHoaDonViewModel;
import duan1_qlbantrasua.ViewModels.SanPhamOption;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author TrungVD
 */
public class OptionSanPhamView extends javax.swing.JDialog {

    /**
     * Creates new form OptionSanPhamView
     */
    private MucDuongService qLDuong;
    private MucDaService qlDa;
    private ToppingService qLTopping;
    private CTGHServiece qLCTGH;
    private DefaultComboBoxModel dcmm;
    double tienPhaiTra;
    
     

    public OptionSanPhamView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        qLDuong = new MucDuongServiceImpl();
        qlDa = new MucDaServiceImpl();
        qLTopping = new ToppingServiceImpl();
        qLCTGH = new CTGHServiceImpl();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Tùy Chọn Sản Phẩm");
        loadCCBDuong(qLDuong.getListMucDuongDB());
        loadCCBDa(qlDa.getListMucDaDB());
        loadCCBTopping(qLTopping.getListToppingDB());
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTenSP = new javax.swing.JLabel();
        lblIDSP = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblMaHoaDon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblGiaSP = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbbMucDuong = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbbMucDa = new javax.swing.JComboBox<>();
        cbbTopping = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        spiSoLuong = new javax.swing.JSpinner();
        btnOkSoLuong = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnDongY = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        lblTenSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTenSP.setForeground(new java.awt.Color(255, 255, 255));
        lblTenSP.setText("Tên Sản Phẩm");

        lblIDSP.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblIDSP.setForeground(new java.awt.Color(255, 255, 255));
        lblIDSP.setText("jLabel7");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mã Hóa Đơn");

        lblMaHoaDon.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblMaHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        lblMaHoaDon.setText("jLabel7");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID Sản Phẩm");

        lblGiaSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGiaSP.setForeground(new java.awt.Color(255, 255, 255));
        lblGiaSP.setText("Giá");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenSP)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIDSP)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblMaHoaDon))
                    .addComponent(lblGiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenSP)
                    .addComponent(lblGiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDSP)
                    .addComponent(jLabel7)
                    .addComponent(lblMaHoaDon)
                    .addComponent(jLabel6))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tùy Chọn Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mức Đường");

        cbbMucDuong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbMucDuongItemStateChanged(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mức Đá");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Topping");

        cbbMucDa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMucDaActionPerformed(evt);
            }
        });

        cbbTopping.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbToppingItemStateChanged(evt);
            }
        });
        cbbTopping.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbToppingMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbbToppingMousePressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan1_qlbantrasua/Views/icon/check.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Số Lượng");

        spiSoLuong.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spiSoLuong.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spiSoLuongStateChanged(evt);
            }
        });

        btnOkSoLuong.setBackground(new java.awt.Color(102, 204, 255));
        btnOkSoLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan1_qlbantrasua/Views/icon/check.png"))); // NOI18N
        btnOkSoLuong.setBorder(null);
        btnOkSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkSoLuongActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tổng Tiền");

        txtTongTien.setText("0");
        txtTongTien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTongTienKeyPressed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Hủy");

        btnDongY.setBackground(new java.awt.Color(0, 204, 51));
        btnDongY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDongY.setForeground(new java.awt.Color(255, 255, 255));
        btnDongY.setText("Đồng Ý");
        btnDongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(spiSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)
                        .addComponent(btnOkSoLuong))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(cbbTopping, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1))
                        .addComponent(cbbMucDa, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbMucDuong, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDongY)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbbMucDuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbMucDa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cbbTopping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOkSoLuong)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(spiSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btnDongY))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongYActionPerformed
        MucDa mucDa = (MucDa) cbbMucDa.getSelectedItem();
        MucDuong mucDuong = (MucDuong) cbbMucDuong.getSelectedItem();
        Topping topping = (Topping) cbbTopping.getSelectedItem();
        int soLuong = (int) spiSoLuong.getValue();
        double donGia = Double.parseDouble(lblGiaSP.getText()) + topping.getGia();
        CTGioHang cTGH = new CTGioHang(lblMaHoaDon.getText(), lblIDSP.getText(),lblTenSP.getText(),
            soLuong, donGia,Double.parseDouble(txtTongTien.getText()), mucDuong.getId(), mucDuong.getTen(),
            mucDa.getId(),mucDa.getTen(), topping.getId(), topping.getTen());
        JOptionPane.showMessageDialog(this, qLCTGH.themCTGH(cTGH));
        dispose();
        //        MainFormView mainFormView = new MainFormView();
        //        mainFormView.setData(sanPhamOption);
        //        this.dispose();
        //        mainFormView.setVisible(true);
    }//GEN-LAST:event_btnDongYActionPerformed

    private void txtTongTienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTongTienKeyPressed

    }//GEN-LAST:event_txtTongTienKeyPressed

    private void btnOkSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkSoLuongActionPerformed
        tienPhaiTra = Double.parseDouble(txtTongTien.getText());
        int soLuong = (int) spiSoLuong.getValue();
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn muốn mua " + soLuong + " sản phẩm đúng không?");
        if (confirm == JOptionPane.YES_OPTION) {
            double gia1SP = tienPhaiTra;
            tienPhaiTra = gia1SP * soLuong;
            txtTongTien.setText(String.valueOf(tienPhaiTra));
        }
    }//GEN-LAST:event_btnOkSoLuongActionPerformed

    private void spiSoLuongStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spiSoLuongStateChanged

    }//GEN-LAST:event_spiSoLuongStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Topping topping = (Topping) cbbTopping.getSelectedItem();
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn chọn " + topping.getTen());
        if (confirm == JOptionPane.YES_OPTION) {
            double tongTien = Double.parseDouble(lblGiaSP.getText()) + topping.getGia();
            txtTongTien.setText(String.valueOf(tongTien));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbbToppingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbToppingMousePressed
        //        System.out.println("hihi");
    }//GEN-LAST:event_cbbToppingMousePressed

    private void cbbToppingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbToppingMouseClicked
        //        System.out.println("hihi");
    }//GEN-LAST:event_cbbToppingMouseClicked

    private void cbbToppingItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbToppingItemStateChanged

    }//GEN-LAST:event_cbbToppingItemStateChanged

    private void cbbMucDaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMucDaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbMucDaActionPerformed

    private void cbbMucDuongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbMucDuongItemStateChanged

    }//GEN-LAST:event_cbbMucDuongItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionSanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionSanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionSanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionSanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OptionSanPhamView dialog = new OptionSanPhamView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    void setEditDaTa(SanPham get) {
        lblIDSP.setText(get.getId());
        lblTenSP.setText(get.getTen() + "(" + get.getSize() + ")");
        lblGiaSP.setText(String.valueOf(get.getGia()));
        txtTongTien.setText(String.valueOf(get.getGia()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDongY;
    private javax.swing.JButton btnOkSoLuong;
    private javax.swing.JComboBox<String> cbbMucDa;
    private javax.swing.JComboBox<String> cbbMucDuong;
    private javax.swing.JComboBox<String> cbbTopping;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblGiaSP;
    private javax.swing.JLabel lblIDSP;
    private javax.swing.JLabel lblMaHoaDon;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JSpinner spiSoLuong;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

    private void loadCCBDuong(ArrayList<MucDuong> listMucDuongDB) {
        dcmm = (DefaultComboBoxModel) cbbMucDuong.getModel();
        for (MucDuong mucDuong : listMucDuongDB) {
            dcmm.addElement(mucDuong);
        }
    }

    private void loadCCBDa(ArrayList<MucDa> listMucDaDB) {
        dcmm = (DefaultComboBoxModel) cbbMucDa.getModel();
        for (MucDa mucDa : listMucDaDB) {
            dcmm.addElement(mucDa);
        }
    }

    private void loadCCBTopping(ArrayList<Topping> listToppingDB) {
        dcmm = (DefaultComboBoxModel) cbbTopping.getModel();
        for (Topping topping : listToppingDB) {
            dcmm.addElement(topping);
        }
    }

    void setEditThongTin(HoaDon get) {
        lblMaHoaDon.setText(get.getMa());
    }

   
}
