/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package duan1_qlbantrasua.Views;

import com.sun.tools.javac.Main;
import duan1_qlbantrasua.DomainModels.HoaDon;
import duan1_qlbantrasua.Services.HoaDonService;
import duan1_qlbantrasua.Services.SanPhamService;
import duan1_qlbantrasua.Services.impl.HoaDonServiceImpl;
import duan1_qlbantrasua.Services.impl.SanPhamServiceImpl;
import duan1_qlbantrasua.ViewModels.DanhSachHoaDon;
import duan1_qlbantrasua.ViewModels.ThongKeSanPham;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFChartSheet;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author TrungVD
 */
public class QuanLyDoanhSo extends javax.swing.JPanel {

    private HoaDonService hds;
    private SanPhamService sps;

    /**
     * Creates new form QuanLyDoanhSo
     */
    public QuanLyDoanhSo() {
        initComponents();
        this.hds = new HoaDonServiceImpl();
        this.sps = new SanPhamServiceImpl();

        java.util.Date ngayTao = new java.util.Date();
        double tongNgay = hds.fillNgaydt(ngayTao);
        int sohdNgay = hds.fillNgayhd(ngayTao);
        int sohdhuyNgay = hds.fillNgayhdh(ngayTao);

        lblDTNgay.setText(tongNgay + "đ");
        lblSoHDNgay.setText(sohdNgay + "");
        lblSoHDHuyNgay.setText(sohdhuyNgay + "");

        double tongTuan = hds.fillTuandt(ngayTao);
        int sohdTuan = hds.fillTuanhd(ngayTao);
        int sohdhuyTuan = hds.fillTuanhdh(ngayTao);

        lblDTTuan.setText(tongTuan + "đ");
        lblSoHDTuan.setText(sohdTuan + "");
        lblSoHDHuyTuan.setText(sohdhuyTuan + "");

        double tongThang = hds.fillThangdt(ngayTao);
        int sohdThang = hds.fillThanghd(ngayTao);
        int sohdhuyThang = hds.fillThanghdh(ngayTao);

        lblDTThang.setText(tongThang + "đ");
        lblSoHDThang.setText(sohdThang + "");
        lblSoHDHuyThang.setText(sohdhuyThang + "");

        loadTableTK();
    }

    public void loc(String txt) {
        DefaultTableModel m = (DefaultTableModel) tblTKSP.getModel();
        m.fireTableDataChanged();
        TableRowSorter sorter = new TableRowSorter(m);
        tblTKSP.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter(txt));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel23 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        lblDTNgay = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSoHDNgay = new javax.swing.JLabel();
        lblSoHDHuyNgay = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        lblDTTuan = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblSoHDTuan = new javax.swing.JLabel();
        lblSoHDHuyTuan = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        lblDTThang = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblSoHDThang = new javax.swing.JLabel();
        lblSoHDHuyThang = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        lblDTKhoang = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblSoHDKhoang = new javax.swing.JLabel();
        lblSoHDHuyKhoang = new javax.swing.JLabel();
        jdsTuKhoang = new com.toedter.calendar.JDateChooser();
        jdsDenKhoang = new com.toedter.calendar.JDateChooser();
        btnChon = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblTKSP = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rdoAll = new javax.swing.JRadioButton();
        rdoDatt = new javax.swing.JRadioButton();
        rdoChuatt = new javax.swing.JRadioButton();
        btnXuat = new javax.swing.JButton();
        cboTop = new javax.swing.JComboBox<>();
        lblClock = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 204, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3), "Quản Lý Doanh Số", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        setForeground(new java.awt.Color(255, 255, 255));

        jPanel23.setBackground(new java.awt.Color(102, 204, 255));
        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3), "Ngày", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel23.setPreferredSize(new java.awt.Dimension(708, 288));

        lblDTNgay.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblDTNgay.setText("300.000 đ");
        lblDTNgay.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblDTNgayInputMethodTextChanged(evt);
            }
        });

        jLabel5.setText("Hóa đơn bán:");

        jLabel6.setText("Hóa đơn hủy:");

        lblSoHDNgay.setText("-");

        lblSoHDHuyNgay.setText("-");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel57)
                .addGap(348, 348, 348))
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSoHDHuyNgay))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSoHDNgay))))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblDTNgay)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(lblDTNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblSoHDNgay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel57)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lblSoHDHuyNgay))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel24.setBackground(new java.awt.Color(102, 204, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3), "Tuần", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel24.setPreferredSize(new java.awt.Dimension(708, 288));

        lblDTTuan.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblDTTuan.setText("300.000 đ");

        jLabel12.setText("Hóa đơn bán:");

        jLabel15.setText("Hóa đơn hủy:");

        lblSoHDTuan.setText("-");

        lblSoHDHuyTuan.setText("-");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblDTTuan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addComponent(jLabel58)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSoHDTuan, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoHDHuyTuan, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(224, 224, 224))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(lblDTTuan, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblSoHDTuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblSoHDHuyTuan))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel25.setBackground(new java.awt.Color(102, 204, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3), "Tháng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel25.setPreferredSize(new java.awt.Dimension(708, 288));

        lblDTThang.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblDTThang.setText("300.000 đ");

        jLabel13.setText("Hóa đơn bán:");

        jLabel16.setText("Hóa đơn hủy:");

        lblSoHDThang.setText("-");

        lblSoHDHuyThang.setText("-");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblDTThang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel59)
                .addGap(31, 31, 31)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSoHDHuyThang, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSoHDThang, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(221, 221, 221))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addComponent(lblDTThang, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblSoHDThang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel59)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblSoHDHuyThang))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel26.setBackground(new java.awt.Color(102, 204, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3), "Khoảng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel26.setPreferredSize(new java.awt.Dimension(708, 288));

        lblDTKhoang.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblDTKhoang.setText("0.0 đ");

        jLabel14.setText("Hóa đơn bán:");

        jLabel17.setText("Hóa đơn hủy:");

        lblSoHDKhoang.setText("-");

        lblSoHDHuyKhoang.setText("-");

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblDTKhoang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addComponent(jLabel60)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSoHDKhoang, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoHDHuyKhoang, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(215, 215, 215))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(lblDTKhoang, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblSoHDKhoang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel60)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblSoHDHuyKhoang))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnChon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan1_qlbantrasua/Views/icon/searh.png"))); // NOI18N
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        jPanel22.setBackground(new java.awt.Color(102, 204, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3), "Thống kê sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel22.setPreferredSize(new java.awt.Dimension(708, 288));

        tblTKSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Giá", "Số lượng bán", "Doanh thu", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTKSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTKSPMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tblTKSP);

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyTyped(evt);
            }
        });

        jLabel1.setText("Tìm kiếm");

        buttonGroup1.add(rdoAll);
        rdoAll.setText("Tất cả");
        rdoAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAllActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoDatt);
        rdoDatt.setText("Còn Bán");
        rdoDatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDattActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoChuatt);
        rdoChuatt.setText("Ngừng bán");
        rdoChuatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoChuattActionPerformed(evt);
            }
        });

        btnXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan1_qlbantrasua/Views/icon/thongke.png"))); // NOI18N
        btnXuat.setText("Xuất Thống Kê Doanh Sản Phẩm");
        btnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatActionPerformed(evt);
            }
        });

        cboTop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Top sản phẩm doanh thu cao nhất", "Top sản phẩm doanh thu thấp nhất" }));
        cboTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboTopMouseClicked(evt);
            }
        });
        cboTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel22Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel22Layout.createSequentialGroup()
                                        .addComponent(rdoAll)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoDatt)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoChuatt))
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(cboTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnXuat))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel22Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel56)
                .addGap(348, 348, 348))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel56))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXuat)
                            .addComponent(cboTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoAll)
                            .addComponent(rdoDatt)
                            .addComponent(rdoChuatt))
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblClock.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jdsTuKhoang, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jdsDenKhoang, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnChon))
                                    .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdsTuKhoang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdsDenKhoang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnChon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblTKSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTKSPMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_tblTKSPMouseClicked

    private void txtTimKiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyTyped
        DefaultTableModel m = (DefaultTableModel) tblTKSP.getModel();
        m.fireTableDataChanged();
        TableRowSorter sorter = new TableRowSorter(m);
        tblTKSP.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter(txtTimKiem.getText()));
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemKeyTyped

    private void rdoAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAllActionPerformed
        loadTableTK();
        loc("");
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoAllActionPerformed

    private void rdoDattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDattActionPerformed
        loadTableTK();
        loc("Còn bán");
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoDattActionPerformed

    private void rdoChuattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoChuattActionPerformed
        loadTableTK();
        loc("Ngừng kinh doanh");
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoChuattActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void lblDTNgayInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblDTNgayInputMethodTextChanged
        java.util.Date ngayTao = new java.util.Date();

        hds.fillNgay(ngayTao);
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDTNgayInputMethodTextChanged

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn lọc không?");
        if (confirm == JOptionPane.YES_OPTION) {
            Date ngayBD = jdsTuKhoang.getDate();
            Date ngayKT = jdsDenKhoang.getDate();
            if (jdsTuKhoang.getDate() == null || jdsDenKhoang.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Không được để trống");
                return;
            }
            double tongKhoang = hds.fillKhoangdt(ngayBD, ngayKT);
            int sohdKhoang = hds.fillKhoanghd(ngayBD, ngayKT);
            int sohdhuyKhoang = hds.fillKhoanghdh(ngayBD, ngayKT);

            lblDTKhoang.setText(tongKhoang + "đ");
            lblSoHDKhoang.setText(sohdKhoang + "");
            lblSoHDHuyKhoang.setText(sohdhuyKhoang + "");

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChonActionPerformed

    private void cboTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTopActionPerformed
        if (cboTop.getSelectedIndex() == 0) {
            loadTableTKTOPNhieu();
        } else {
            loadTableTOPIt();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTopActionPerformed

    private void cboTopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboTopMouseClicked

//        if(cboTop.getSelectedIndex()==0){
//            loadTableTKTOPNhieu();
//        }else{
//            loadTableTOPIt();
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTopMouseClicked

    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
        try {
            //System.setProperty("log4j.configurationFile", "./path_to_the_log4j2_config_file/log4j2.xml");

            //Logger log = LogManager.getLogger(LogExample.class.getName());
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn xuất thống kê không?");
            if (confirm == JOptionPane.YES_OPTION) {
                JFileChooser j = new JFileChooser("C:\\Users\\TrungVD\\OneDrive\\MyPC\\TrungVDPD21738_SOF2041_JDBC1\\DuAn1QuanLyBanTraSua\\exel");
                j.setDialogTitle("Hãy chọn địa chỉ muốn xuất file !");
                int rs = j.showSaveDialog(null);
                if (rs == JFileChooser.APPROVE_OPTION) {
                    String Path = j.getSelectedFile().getAbsolutePath();
                    String name = j.getSelectedFile().getName();
                    String exclePath = Path + ".xls";
                    System.out.println(name);
                    FileOutputStream fileOut = null;

                    XSSFWorkbook workbook = new XSSFWorkbook();
                    XSSFSheet sheet = workbook.createSheet("Thống kê sản phẩm");

                    XSSFRow row = null;
                    Cell cell = null;

                    row = sheet.createRow(0);
                    int rownum = 0;

                    cell = row.createCell(0, CellType.STRING);
                    cell.setCellValue("Mã SP");

                    cell = row.createCell(1, CellType.STRING);
                    cell.setCellValue("Tên SP");

                    cell = row.createCell(2, CellType.STRING);
                    cell.setCellValue("Giá");

                    cell = row.createCell(3, CellType.STRING);
                    cell.setCellValue("Số lượng bán");

                    cell = row.createCell(4, CellType.STRING);
                    cell.setCellValue("Doanh thu");

                    cell = row.createCell(5, CellType.STRING);
                    cell.setCellValue("Trạng thái");

                    System.out.println(exclePath);
                    try {
                        fileOut = new FileOutputStream(exclePath);
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }

                    for (ThongKeSanPham tk : this.sps.getListTKSanPham()) {
                        rownum++;
                        row = sheet.createRow(rownum);

                        cell = row.createCell(0, CellType.STRING);
                        cell.setCellValue(tk.getMa());

                        cell = row.createCell(1, CellType.STRING);
                        cell.setCellValue(tk.getTen());

                        cell = row.createCell(2, CellType.STRING);
                        cell.setCellValue(tk.getGia());

                        cell = row.createCell(3, CellType.STRING);
                        cell.setCellValue(tk.getSoLuongBan());

                        cell = row.createCell(4, CellType.STRING);
                        cell.setCellValue(tk.getDoanhThu(tk.getGia(), tk.getSoLuongBan()));

                        cell = row.createCell(5, CellType.STRING);
                        cell.setCellValue(tk.getTrangThai());
                    }
                    try {
                        workbook.write(fileOut);
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                    try {
                        fileOut.close();
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            }
            JOptionPane.showMessageDialog(this, "Xuất hóa đơn thành công!");
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXuatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnXuat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboTop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JScrollPane jScrollPane9;
    private com.toedter.calendar.JDateChooser jdsDenKhoang;
    private com.toedter.calendar.JDateChooser jdsTuKhoang;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblDTKhoang;
    private javax.swing.JLabel lblDTNgay;
    private javax.swing.JLabel lblDTThang;
    private javax.swing.JLabel lblDTTuan;
    private javax.swing.JLabel lblSoHDHuyKhoang;
    private javax.swing.JLabel lblSoHDHuyNgay;
    private javax.swing.JLabel lblSoHDHuyThang;
    private javax.swing.JLabel lblSoHDHuyTuan;
    private javax.swing.JLabel lblSoHDKhoang;
    private javax.swing.JLabel lblSoHDNgay;
    private javax.swing.JLabel lblSoHDThang;
    private javax.swing.JLabel lblSoHDTuan;
    private javax.swing.JRadioButton rdoAll;
    private javax.swing.JRadioButton rdoChuatt;
    private javax.swing.JRadioButton rdoDatt;
    private javax.swing.JTable tblTKSP;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    private void loadTableTK() {
        DefaultTableModel model = (DefaultTableModel) this.tblTKSP.getModel();
        model.setRowCount(0);
        for (ThongKeSanPham tk : this.sps.getListTKSanPham()) {
            Object[] rowData = {
                tk.getMa(),
                tk.getTen(),
                tk.getGia(),
                tk.getSoLuongBan(),
                tk.getDoanhThu(tk.getGia(), tk.getSoLuongBan()),
                tk.getTrangThai() == 0 ? "Còn bán" : "Ngừng kinh doanh"
            };

            model.addRow(rowData);
        }
    }

    private void loadTableTKTOPNhieu() {
        DefaultTableModel model = (DefaultTableModel) this.tblTKSP.getModel();
        model.setRowCount(0);
        for (ThongKeSanPham tk : this.sps.getListTKSanPhamTOPSLBNhieu()) {
            Object[] rowData = {
                tk.getMa(),
                tk.getTen(),
                tk.getGia(),
                tk.getSoLuongBan(),
                tk.getDoanhThu(tk.getGia(), tk.getSoLuongBan()),
                tk.getTrangThai() == 0 ? "Còn bán" : "Ngừng kinh doanh"
            };

            model.addRow(rowData);
        }
    }

    private void loadTableTOPIt() {
        DefaultTableModel model = (DefaultTableModel) this.tblTKSP.getModel();
        model.setRowCount(0);
        for (ThongKeSanPham tk : this.sps.getListTKSanPhamTOPSLBIt()) {
            Object[] rowData = {
                tk.getMa(),
                tk.getTen(),
                tk.getGia(),
                tk.getSoLuongBan(),
                tk.getDoanhThu(tk.getGia(), tk.getSoLuongBan()),
                tk.getTrangThai() == 0 ? "Còn bán" : "Ngừng kinh doanh"
            };

            model.addRow(rowData);
        }
    }
}
